Feature quetion update
vafedorova/my_repo pull request #1
Opened 2022-09-29 15:16 UTC by VPlotnikov2006

2022-10-02 12:13 UTC, VPlotnikov2006 commented
Варвара Кирилловна

2022-10-03 17:13 UTC, vafedorova commented on main.cpp
> +#include <stdlib.h>
Мне кажется, лучше cstdlib включить.

2022-10-03 17:21 UTC, vafedorova commented on main.cpp
> +    map<string, int> answers;
Тут лучше использовать unordered_map, потому что она реализована как хеш-таблица и работает эффективнее)

2022-10-03 17:22 UTC, vafedorova commented on main.cpp
> +    }
return 0; ?

2022-10-03 17:25 UTC, vafedorova requested changes
Посмотри, пожалуйста, что я написала)

2022-10-03 17:35 UTC, VPlotnikov2006 commented on main.cpp
> +    }
После чего ты хочешь делать return?

2022-10-03 17:36 UTC, VPlotnikov2006 commented on main.cpp
> +    map<string, int> answers;
В такой простой программе +-0.00001 секунды ничего не изменят

2022-10-03 17:36 UTC, VPlotnikov2006 commented on main.cpp
> +#include <stdlib.h>
Это одно и тоже

2023-03-19 18:34 UTC, closed without merging